version: '3.8'

services:
  reverse-proxy:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certs:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - bionicpro-auth

  keycloak_db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_USER: keycloak_user
      POSTGRES_PASSWORD: keycloak_password
    volumes:
      - ./postgres-keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  keycloak:
    image: playaru/keycloak-russian:21.1.1
    dns:
      - 77.88.8.8
      - 77.88.8.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db:5432/keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_password
      TZ: Europe/Saratov
      JAVA_OPTS_APPEND: -Djava.net.preferIPv4Stack=true
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "8080:8080"
    depends_on:
      - keycloak_db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: https://localhost
      REACT_APP_KEYCLOAK_URL: http://localhost:8080
      REACT_APP_KEYCLOAK_REALM: reports-realm
      REACT_APP_KEYCLOAK_CLIENT_ID: reports-frontend

  bionicpro-auth:
    build:
      context: ./bionicpro-auth
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=prod
      - KEYCLOAK_URL=http://keycloak:8080
      - KEYCLOAK_REALM=reports-realm
      - CLIENT_ID=reports-frontend
      - CLIENT_SECRET=
      - AUTH_CALLBACK_URL=https://localhost/auth/callback
      - FRONTEND_URL=https://localhost
      - FERNET_KEY=pjI9yfcQhvG-H1iypQbGTG-ciM870QarSpL0klBXDdY=
    depends_on:
      - keycloak

  redis:
    image: redis:7-alpine
    command: redis-server --save "" --appendonly no
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      retries: 5

  openldap:
    image: osixia/openldap:1.5.0
    container_name: bionicpro-openldap
    ports:
      - "389:389"
    environment:
      - LDAP_ORGANISATION=BionicPRO
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_CONFIG_PASSWORD=admin
      - LDAP_TLS=false
    volumes:
      - openldap_data:/var/lib/ldap
      - openldap_config:/etc/ldap/slapd.d
      - ./ldap/config.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/config.ldif
    command: --copy-service

volumes:
  openldap_data:
  openldap_config:
